/** Preview-level config — 4-axis modes toolbar + a11y + components CSS.
 *
 * Merges:
 * - The mode-toolbar system from tier0-foundations-oklch (color / contrast /
 *   vision / density via body data-attrs)
 * - The a11y addon test config (mode: 'todo' until violations are triaged)
 * - Component CSS + generated tokens CSS imports
 */

// Tokens CSS (generated by design/tokens/scripts/generate-css.py from
// semantic.tokens.json) — declares the public CSS custom properties:
// --surface-*, --text-*, --solid-*, --status-*, --radius-*, --motion-*, etc.
import '../design/tokens/dist/tokens.css';

// Component styles — consume the tokens above
import '../design/components/components.css';

/** @type { import('@storybook/html-vite').Preview } */
const preview = {
  parameters: {
    layout: 'fullscreen',
    backgrounds: { disable: true }, // canvas bg comes from `--surface-canvas` driven by the `color` mode
    controls: {
      matchers: { color: /(background|color)$/i, date: /Date$/i },
    },

    // Sidebar order — Tokens (Core → Primitives → Semantic) first, then
    // Components, then Patterns. Top-level groups not in this list append
    // alphabetically after.
    options: {
      storySort: {
        order: [
          'Tokens', ['Core', 'Primitives', 'Semantic'],
          'Components',
          'Patterns',
        ],
      },
    },

    // ===== A11Y (axe-core) — mode 'todo' = report violations without failing =====
    a11y: {
      test: 'todo',
      config: { rules: [] },
    },
  },

  // Four orthogonal mode axes. Each becomes a toolbar dropdown.
  globalTypes: {
    color: {
      name: 'Color mode',
      description: 'Light / dark mode',
      defaultValue: 'light',
      toolbar: {
        icon: 'mirror',
        items: [
          { value: 'light', title: 'Light' },
          { value: 'dark',  title: 'Dark' },
        ],
        dynamicTitle: true,
      },
    },
    contrast: {
      name: 'Contrast',
      description: 'Default / enhanced contrast',
      defaultValue: 'default',
      toolbar: {
        icon: 'contrast',
        items: [
          { value: 'default',  title: 'Default contrast' },
          { value: 'enhanced', title: 'Enhanced contrast' },
        ],
        dynamicTitle: true,
      },
    },
    vision: {
      name: 'Vision',
      description: 'Color vision simulation',
      defaultValue: 'default',
      toolbar: {
        icon: 'eye',
        items: [
          { value: 'default',       title: 'Trichromat' },
          { value: 'deuteranopia',  title: 'Deuteranopia (no green)' },
          { value: 'protanopia',    title: 'Protanopia (no red)' },
          { value: 'tritanopia',    title: 'Tritanopia (no blue)' },
          { value: 'achromatopsia', title: 'Achromatopsia (monochrome)' },
        ],
        dynamicTitle: true,
      },
    },
    density: {
      name: 'Density',
      description: 'Layout density',
      defaultValue: 'default',
      toolbar: {
        icon: 'ruler',
        items: [
          { value: 'compact',  title: 'Compact' },
          { value: 'default',  title: 'Comfortable' },
          { value: 'spacious', title: 'Spacious' },
        ],
        dynamicTitle: true,
      },
    },
  },

  // Apply the active modes to <body> via data-* attributes.
  // Stories and helpers read these via `document.body.dataset.*`.
  // Tokens CSS targets these via `[data-color="dark"]`, `[data-density="compact"]`, etc.
  decorators: [
    (storyFn, context) => {
      const body = document.body;
      body.dataset.color    = context.globals.color    ?? 'light';
      body.dataset.contrast = context.globals.contrast ?? 'default';
      body.dataset.vision   = context.globals.vision   ?? 'default';
      body.dataset.density  = context.globals.density  ?? 'default';
      body.style.colorScheme = body.dataset.color;
      return storyFn();
    },
  ],
};

export default preview;
